"""MLPrep CLI.

Commands
────────
  inspect    Profile a dataset and display a summary.
  preprocess Preprocess a dataset and export results + pipeline.
  transform  Apply a saved pipeline to new data.

Preprocessing mode selection (preprocess command)
──────────────────────────────────────────────────
  1. Expert mode  : one or more preprocessing flags supplied
  2. Config mode  : --config path supplied
  3. Interactive  : interactive terminal, no flags → wizard
  4. Default mode : non-interactive, no flags → sensible defaults

Combining --config with individual preprocessing flags is rejected.

Security note (transform command)
──────────────────────────────────
Only load preprocessor.joblib files that were generated by trusted MLPrep
runs. Python joblib/pickle can execute arbitrary code if the file is tampered
with.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import typer
from rich.console import Console
from sklearn.compose import ColumnTransformer

from mlprep.config import PreprocessConfig, load_config
from mlprep.display import display_profile
from mlprep.io import load_validated_dataset
from mlprep.preprocess.pipeline import (
    preprocess_dataset,
    transform_dataset,
)
from mlprep.profiler import profile_dataset
from mlprep.reports import build_report, display_report, save_report_json
from mlprep.ui import build_config_interactive

app = typer.Typer(
    help="MLPrep — reproducible ML preprocessing CLI.",
    no_args_is_help=True,
)
console = Console()
err_console = Console(stderr=True, style="bold red")


# ── inspect ───────────────────────────────────────────────────────────────────


@app.command()
def inspect(
    file_path: Path = typer.Argument(..., help="Path to the input CSV file."),  # noqa: B008
) -> None:
    """Profile a dataset and display a summary of columns, types, and missing values."""
    try:
        df = load_validated_dataset(file_path)
        display_profile(df)
    except (ValueError, SystemExit) as error:
        if isinstance(error, ValueError):
            err_console.print(f"Error: {error}")
            raise typer.Exit(code=1)
        raise


# ── preprocess ────────────────────────────────────────────────────────────────


@app.command()
def preprocess(
    file_path: Path = typer.Argument(..., help="Path to the input CSV file."),  # noqa: B008
    output: Path = typer.Option(  # noqa: B008
        Path("./data/processed.csv"),
        "--output",
        "-o",
        help="Where to save the processed CSV.",
    ),
    config_path: Path | None = typer.Option(  # noqa: B008
        None,
        "--config",
        "-c",
        help="Path to a YAML configuration file.",
    ),
    strategy: str | None = typer.Option(
        None,
        "--strategy",
        help="Numerical missing-value strategy (median | mean | constant).",
    ),
    cat_strategy: str | None = typer.Option(
        None,
        "--cat-strategy",
        help="Categorical missing-value strategy (most_frequent | constant).",
    ),
) -> None:
    """Preprocess a dataset: impute, encode, scale, and export results.

    Outputs:
      processed.csv       — transformed dataset\n
      preprocessor.joblib — fitted sklearn pipeline\n
      report.json         — preprocessing report
    """
    # ── Guard: reject --config + individual flags ──────────────────────────
    expert_flags = [strategy, cat_strategy]
    if config_path is not None and any(f is not None for f in expert_flags):
        err_console.print(
            "Error: Cannot combine --config with preprocessing options "
            "(--strategy, --cat-strategy). "
            "Use one interface at a time."
        )
        raise typer.Exit(code=1)

    # ── Load dataset ───────────────────────────────────────────────────────
    try:
        df = load_validated_dataset(file_path)
    except ValueError as error:
        err_console.print(f"Error: {error}")
        raise typer.Exit(code=1)

    # ── Build PreprocessConfig ─────────────────────────────────────────────
    config = _resolve_config(config_path, strategy, cat_strategy)
    if config is None:
        # User cancelled the wizard
        console.print("[yellow]Cancelled.[/yellow]")
        raise typer.Exit()

    console.print(f"\n[bold cyan]Strategy:[/bold cyan] numerical={config.numerical_strategy}, categorical={config.categorical_strategy}")

    # ── Preprocess ─────────────────────────────────────────────────────────
    try:
        processed_df, preprocessor = preprocess_dataset(df, config)
    except ValueError as error:
        err_console.print(f"Error during preprocessing: {error}")
        raise typer.Exit(code=1)

    # ── Save outputs ───────────────────────────────────────────────────────
    output.parent.mkdir(parents=True, exist_ok=True)
    pipeline_output = output.parent / "preprocessor.joblib"
    report_output = output.parent / "report.json"

    processed_df.to_csv(output, index=False)
    joblib.dump(preprocessor, pipeline_output)

    # ── Build + display + save report ──────────────────────────────────────
    profile = profile_dataset(df)
    report = build_report(
        config=config,
        profile=profile,
        input_path=file_path,
        output_path=output,
        pipeline_path=pipeline_output,
        report_path=report_output,
    )
    display_report(report)
    save_report_json(report, report_output)

    console.print(f"\n[green]✓ Processed dataset saved to: {output}[/green]")
    console.print(f"[green]✓ Pipeline saved to: {pipeline_output}[/green]")
    console.print(f"[green]✓ Report saved to: {report_output}[/green]")


# ── transform ─────────────────────────────────────────────────────────────────


@app.command()
def transform(
    file_path: Path = typer.Argument(..., help="Path to the new input CSV file."),  # noqa: B008
    pipeline: Path = typer.Argument(..., help="Path to a saved preprocessor.joblib."),  # noqa: B008
    output: Path = typer.Option(  # noqa: B008
        Path("./data/transformed.csv"),
        "--output",
        "-o",
        help="Where to save the transformed CSV.",
    ),
) -> None:
    """Apply a saved preprocessing pipeline to new data without refitting.

    Security: only load preprocessor.joblib files from trusted MLPrep runs.
    """
    try:
        _validate_pipeline_file(pipeline)
        df = load_validated_dataset(file_path)
        preprocessor = _load_pipeline(pipeline)
    except ValueError as error:
        err_console.print(f"Error: {error}")
        raise typer.Exit(code=1)

    # ── Column compatibility check ─────────────────────────────────────────
    try:
        df = _prepare_dataframe_for_transform(df, preprocessor)
    except ValueError as error:
        err_console.print(f"Error: {error}")
        raise typer.Exit(code=1)

    processed_df = transform_dataset(df, preprocessor)

    output.parent.mkdir(parents=True, exist_ok=True)
    processed_df.to_csv(output, index=False)

    console.print(f"[green]✓ Transformed dataset saved to: {output}[/green]")


# ── Internal helpers ──────────────────────────────────────────────────────────


def _resolve_config(
    config_path: Path | None,
    strategy: str | None,
    cat_strategy: str | None,
) -> PreprocessConfig | None:
    """Resolve a ``PreprocessConfig`` from whichever interface was used."""

    # 1. Config file mode
    if config_path is not None:
        try:
            return load_config(config_path)
        except ValueError as error:
            err_console.print(f"Error loading config: {error}")
            raise typer.Exit(code=1)

    # 2. Expert mode — at least one flag was passed
    if strategy is not None or cat_strategy is not None:
        try:
            return PreprocessConfig(
                numerical_strategy=strategy or "median",
                categorical_strategy=cat_strategy or "most_frequent",
            )
        except ValueError as error:
            err_console.print(f"Error: {error}")
            raise typer.Exit(code=1)

    # 3. Interactive or default mode
    return build_config_interactive()


def _validate_pipeline_file(path: Path) -> None:
    """Raise ``ValueError`` if *path* is not a readable .joblib file."""
    if not path.exists():
        raise ValueError(f"Pipeline file not found: {path}")
    if path.suffix.lower() != ".joblib":
        raise ValueError(
            f"Expected a .joblib file, got: {path.suffix!r}. "
            "Only load pipeline files generated by MLPrep."
        )


def _load_pipeline(path: Path) -> ColumnTransformer:
    """Load and validate a joblib file as a ``ColumnTransformer``."""
    obj = joblib.load(path)
    if not isinstance(obj, ColumnTransformer):
        raise TypeError(
            "The pipeline file does not contain a valid MLPrep preprocessor. "
            f"Expected ColumnTransformer, got {type(obj).__name__}."
        )
    return obj


def _prepare_dataframe_for_transform(
    df: pd.DataFrame,  # noqa: F821
    preprocessor: ColumnTransformer,
) -> pd.DataFrame:  # noqa: F821
    """Validate column compatibility and reorder/drop columns for transform.

    Rules:
    - Required columns (those the preprocessor was trained on) must be present.
      Missing required columns → hard error.
    - Extra columns (present in new data but not in training) → warn + ignore.
    - Column order does not matter — we reorder to match training.
    """

    # Collect the columns the preprocessor was fitted on
    required_columns: list[str] = []
    for _, _, cols in preprocessor.transformers_:
        if isinstance(cols, list):
            required_columns.extend(cols)

    if not required_columns:
        # Fallback: just pass the df as-is (edge case)
        return df

    input_columns = set(df.columns)
    required_set = set(required_columns)

    # Hard error for missing required columns
    missing = required_set - input_columns
    if missing:
        raise ValueError(
            f"New data is missing columns that the pipeline was trained on: "
            f"{sorted(missing)}. "
            "Ensure the input file contains all required columns."
        )

    # Warn + ignore extra columns
    extra = input_columns - required_set
    if extra:
        console.print(
            f"[yellow]⚠ Warning: ignoring {len(extra)} extra column(s) not seen "
            f"during training: {sorted(extra)}[/yellow]"
        )

    # Return df with only the required columns in training order
    return df[required_columns]


if __name__ == "__main__":
    app()
