"""MLPrep CLI.

Commands
────────
  inspect    Profile a dataset (Rich table or JSON).
  preprocess Preprocess a dataset and export results + pipeline.
  transform  Apply a saved pipeline to new data.

Preprocessing mode selection
─────────────────────────────
  1. Config mode  : --config supplied
  2. Expert mode  : --strategy / --cat-strategy supplied
  3. Interactive  : interactive terminal, no flags → wizard
  4. Default mode : non-interactive, no flags → sensible defaults

Rules
─────
  • --config + preprocessing flags → rejected
  • Missing required columns at transform time → hard error
  • Extra columns at transform time → warn + ignore
  • Column order does not matter at transform time

Exit codes
──────────
  0  Success
  1  Error (bad input, invalid config, preprocessing failure, write failure)

Security (transform command)
─────────────────────────────
Only load preprocessor.joblib files generated by trusted MLPrep runs.
Python joblib/pickle can execute arbitrary code in tampered files.
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import joblib
import pandas as pd
import typer
from rich.console import Console
from sklearn.compose import ColumnTransformer

from mlprep.config import PreprocessConfig, load_config
from mlprep.display import display_profile
from mlprep.io import load_validated_dataset, save_dataframe
from mlprep.logging_config import get_logger, setup_logging
from mlprep.preprocess.pipeline import preprocess_dataset, transform_dataset
from mlprep.profiler import profile_dataset
from mlprep.quality import display_quality_warnings, run_quality_checks
from mlprep.reports import build_report, display_report, save_report_json
from mlprep.ui import build_config_interactive

log = get_logger(__name__)

app = typer.Typer(
    help=(
        "MLPrep — reproducible ML preprocessing CLI.\n\n"
        "Profile datasets, apply configurable preprocessing pipelines, "
        "and export reusable scikit-learn pipelines.\n\n"
        "Supports interactive wizard, expert CLI flags, and YAML configuration."
    ),
    no_args_is_help=True,
    rich_markup_mode="rich",
)
console = Console()
err_console = Console(stderr=True, style="bold red")

# ── Shared option types ───────────────────────────────────────────────────────

_VerboseOpt = Annotated[
    bool,
    typer.Option("--verbose", "-v", help="Show detailed logging output."),
]

_FormatOpt = Annotated[
    str,
    typer.Option(
        "--format",
        "-f",
        help="Output format: [bold]rich[/bold] (default) or [bold]json[/bold].",
    ),
]


# ── inspect ───────────────────────────────────────────────────────────────────


@app.command()
def inspect(
    file_path: Path = typer.Argument(  # noqa: B008
        ...,
        help="Path to the input CSV file.",
    ),
    fmt: _FormatOpt = "rich",
    no_warnings: bool = typer.Option(
        False, "--no-warnings", help="Suppress data quality warnings."
    ),
    verbose: _VerboseOpt = False,
) -> None:
    """Profile a dataset: column types, missing values, and data quality warnings.

    \b
    Examples:
      mlprep inspect data.csv
      mlprep inspect data.csv --format json
      mlprep inspect data.csv --no-warnings
    """
    setup_logging(verbose)

    try:
        log.info("Loading dataset: %s", file_path)
        df = load_validated_dataset(file_path)
        log.info("Loaded %d rows, %d columns", len(df), len(df.columns))
    except ValueError as error:
        err_console.print(f"✗ Error: {error}")
        raise typer.Exit(code=1)

    display_profile(df, fmt=fmt)

    if not no_warnings:
        warnings = run_quality_checks(df)
        if warnings:
            display_quality_warnings(warnings)
        else:
            log.info("No data quality issues found.")


# ── preprocess ────────────────────────────────────────────────────────────────


@app.command()
def preprocess(
    file_path: Path = typer.Argument(  # noqa: B008
        ...,
        help="Path to the input CSV file.",
    ),
    output: Path = typer.Option(  # noqa: B008
        Path("./data/processed.csv"),
        "--output", "-o",
        help="Where to save the processed CSV.",
    ),
    config_path: Path | None = typer.Option(  # noqa: B008
        None,
        "--config", "-c",
        help="Path to a YAML configuration file.",
    ),
    strategy: str | None = typer.Option(
        None,
        "--strategy",
        help="Numerical missing-value strategy: median | mean | constant.",
    ),
    cat_strategy: str | None = typer.Option(
        None,
        "--cat-strategy",
        help="Categorical missing-value strategy: most_frequent | constant.",
    ),
    no_warnings: bool = typer.Option(
        False, "--no-warnings", help="Suppress data quality warnings."
    ),
    verbose: _VerboseOpt = False,
) -> None:
    """Preprocess a dataset: impute missing values, encode, scale, and export.

    [bold]Outputs[/bold] (saved next to --output):
      processed.csv       — transformed dataset
      preprocessor.joblib — fitted sklearn pipeline (reusable)
      report.json         — machine-readable preprocessing report

    \b
    Examples:
      mlprep preprocess data.csv
      mlprep preprocess data.csv --strategy mean --cat-strategy constant
      mlprep preprocess data.csv --config config.yaml
      mlprep preprocess data.csv --output results/clean.csv --verbose
    """
    setup_logging(verbose)

    # ── Guard: reject --config + individual flags ──────────────────────────
    if config_path is not None and any(f is not None for f in [strategy, cat_strategy]):
        err_console.print(
            "✗ Error: Cannot combine --config with preprocessing options "
            "(--strategy, --cat-strategy). Use one interface at a time."
        )
        raise typer.Exit(code=1)

    # ── Load dataset ───────────────────────────────────────────────────────
    try:
        log.info("Loading dataset: %s", file_path)
        df = load_validated_dataset(file_path)
        log.info("Loaded %d rows, %d columns", len(df), len(df.columns))
    except ValueError as error:
        err_console.print(f"✗ Error: {error}")
        raise typer.Exit(code=1)

    console.print(f"[green]✓[/green] Dataset loaded — {len(df):,} rows, {len(df.columns)} columns")

    # ── Data quality checks ────────────────────────────────────────────────
    if not no_warnings:
        log.info("Running data quality checks")
        warnings = run_quality_checks(df)
        if warnings:
            display_quality_warnings(warnings)

    # ── Build PreprocessConfig ─────────────────────────────────────────────
    config = _resolve_config(config_path, strategy, cat_strategy)
    if config is None:
        console.print("[yellow]Cancelled.[/yellow]")
        raise typer.Exit()

    log.info(
        "Config: numerical=%s, categorical=%s",
        config.numerical_strategy,
        config.categorical_strategy,
    )
    console.print(
        f"[green]✓[/green] Config ready — "
        f"numerical=[bold]{config.numerical_strategy}[/bold], "
        f"categorical=[bold]{config.categorical_strategy}[/bold]"
    )

    # ── Preprocess ─────────────────────────────────────────────────────────
    try:
        log.info("Fitting and transforming dataset")
        processed_df, fitted_preprocessor = preprocess_dataset(df, config)
        log.info("Preprocessing complete — output shape: %s", processed_df.shape)
    except ValueError as error:
        err_console.print(f"✗ Error during preprocessing: {error}")
        raise typer.Exit(code=1)

    console.print(
        f"[green]✓[/green] Preprocessing complete — "
        f"{processed_df.shape[0]:,} rows, {processed_df.shape[1]} features"
    )

    # ── Save outputs ───────────────────────────────────────────────────────
    output.parent.mkdir(parents=True, exist_ok=True)
    pipeline_output = output.parent / "preprocessor.joblib"
    report_output = output.parent / "report.json"

    try:
        log.info("Saving processed dataset to: %s", output)
        save_dataframe(processed_df, output)
        log.info("Saving pipeline to: %s", pipeline_output)
        joblib.dump(fitted_preprocessor, pipeline_output)
    except ValueError as error:
        err_console.print(f"✗ Error saving outputs: {error}")
        raise typer.Exit(code=1)

    # ── Build + display + save report ──────────────────────────────────────
    profile = profile_dataset(df)
    report = build_report(
        config=config,
        profile=profile,
        input_path=file_path,
        output_path=output,
        pipeline_path=pipeline_output,
        report_path=report_output,
    )

    try:
        save_report_json(report, report_output)
        log.info("Report saved to: %s", report_output)
    except (OSError, ValueError) as error:
        err_console.print(f"✗ Warning: Could not save report: {error}")

    display_report(report)

    console.print(f"\n[green]✓[/green] Processed dataset → [bold]{output}[/bold]")
    console.print(f"[green]✓[/green] Pipeline         → [bold]{pipeline_output}[/bold]")
    console.print(f"[green]✓[/green] Report           → [bold]{report_output}[/bold]")


# ── transform ─────────────────────────────────────────────────────────────────


@app.command()
def transform(
    file_path: Path = typer.Argument(  # noqa: B008
        ...,
        help="Path to the new input CSV file.",
    ),
    pipeline: Path = typer.Argument(  # noqa: B008
        ...,
        help="Path to a saved preprocessor.joblib file.",
    ),
    output: Path = typer.Option(  # noqa: B008
        Path("./data/transformed.csv"),
        "--output", "-o",
        help="Where to save the transformed CSV.",
    ),
    verbose: _VerboseOpt = False,
) -> None:
    """Apply a saved preprocessing pipeline to new data without refitting.

    [bold]Security[/bold]: only load .joblib files generated by trusted MLPrep runs.
    Python's joblib/pickle can execute arbitrary code in tampered files.

    \b
    Examples:
      mlprep transform new_data.csv data/preprocessor.joblib
      mlprep transform new_data.csv data/preprocessor.joblib --output results/out.csv
    """
    setup_logging(verbose)

    try:
        log.info("Validating pipeline file: %s", pipeline)
        _validate_pipeline_file(pipeline)
        log.info("Loading dataset: %s", file_path)
        df = load_validated_dataset(file_path)
        log.info("Loading pipeline")
        fitted_preprocessor = _load_pipeline(pipeline)
    except (ValueError, TypeError) as error:
        err_console.print(f"✗ Error: {error}")
        raise typer.Exit(code=1)

    console.print(f"[green]✓[/green] Dataset loaded — {len(df):,} rows, {len(df.columns)} columns")

    # ── Column compatibility ────────────────────────────────────────────────
    try:
        df = _prepare_dataframe_for_transform(df, fitted_preprocessor)
    except ValueError as error:
        err_console.print(f"✗ Error: {error}")
        raise typer.Exit(code=1)

    log.info("Transforming dataset")
    processed_df = transform_dataset(df, fitted_preprocessor)
    log.info("Transform complete — output shape: %s", processed_df.shape)

    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        save_dataframe(processed_df, output)
    except ValueError as error:
        err_console.print(f"✗ Error saving output: {error}")
        raise typer.Exit(code=1)

    console.print(f"[green]✓[/green] Transformed dataset → [bold]{output}[/bold]")


# ── Internal helpers ──────────────────────────────────────────────────────────


def _resolve_config(
    config_path: Path | None,
    strategy: str | None,
    cat_strategy: str | None,
) -> PreprocessConfig | None:
    """Return a ``PreprocessConfig`` from whichever interface was used."""

    if config_path is not None:
        try:
            log.info("Loading config from: %s", config_path)
            return load_config(config_path)
        except (ValueError, TypeError) as error:
            err_console.print(f"✗ Error loading config: {error}")
            raise typer.Exit(code=1)

    if strategy is not None or cat_strategy is not None:
        log.info("Expert mode: strategy=%s, cat_strategy=%s", strategy, cat_strategy)
        try:
            return PreprocessConfig(
                numerical_strategy=strategy or "median",
                categorical_strategy=cat_strategy or "most_frequent",
            )
        except ValueError as error:
            err_console.print(f"✗ Error: {error}")
            raise typer.Exit(code=1)

    log.info("No flags — entering interactive/default mode")
    return build_config_interactive()


def _validate_pipeline_file(path: Path) -> None:
    """Raise ``ValueError`` if *path* is not a valid .joblib file."""
    if not path.exists():
        raise ValueError(f"Pipeline file not found: {path}")
    if path.suffix.lower() != ".joblib":
        raise ValueError(
            f"Expected a .joblib file, got: {path.suffix!r}. "
            "Only load pipeline files generated by MLPrep."
        )


def _load_pipeline(path: Path) -> ColumnTransformer:
    """Load and validate a joblib file as a ``ColumnTransformer``."""
    obj = joblib.load(path)
    if not isinstance(obj, ColumnTransformer):
        raise TypeError(
            "The pipeline file does not contain a valid MLPrep preprocessor. "
            f"Expected ColumnTransformer, got {type(obj).__name__}."
        )
    return obj


def _prepare_dataframe_for_transform(
    df: pd.DataFrame,
    preprocessor: ColumnTransformer,
) -> pd.DataFrame:
    """Validate column compatibility and reorder columns for transform.

    Rules:
    - Missing required columns → hard error
    - Extra columns → warn + ignore
    - Column order → normalised to training order
    """

    required_columns: list[str] = []
    for _, _, cols in preprocessor.transformers_:
        if isinstance(cols, list):
            required_columns.extend(cols)

    if not required_columns:
        return df

    input_columns = set(df.columns)
    required_set = set(required_columns)

    missing = required_set - input_columns
    if missing:
        raise ValueError(
            f"New data is missing columns that the pipeline was trained on: "
            f"{sorted(missing)}. "
            "Ensure the input file contains all required columns."
        )

    extra = input_columns - required_set
    if extra:
        log.warning(
            "Ignoring %d extra column(s) not seen during training: %s",
            len(extra),
            sorted(extra),
        )
        console.print(
            f"[yellow]⚠ Warning: ignoring {len(extra)} extra column(s) "
            f"not seen during training: {sorted(extra)}[/yellow]"
        )

    return df[required_columns]


if __name__ == "__main__":
    app()
